typography_spectrum: 0.83384
color:
  brandColors:
    - '#f2f6f9'
    - '#28411a'
    - '#de1b21'
    - '#d0c3bc'
    - '#af6f49'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.67346
analytics:
  google: null
  facebook: null
  twitter: null
name: 'lexiconic, inc.'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: www.lexiconic.io
    type: external
favicon: null
title: Scrum | ITIL | Project Consulting
purpose: []
