name: 'lexiconic, inc.'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17963
title: Where does the title actually appear?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a17'
    - '#fefefe'
    - '#7a6051'
    - '#a09baa'
    - '#972712'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
