name: lexiconic
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12238317262381315
title: Site Title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7ddd1'
    - '#19539c'
    - '#afbab2'
    - '#0f211e'
    - '#6e7867'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
