name: 'lexiconic, inc.'
favicon: null
layout_spectrum: 0.68973
typography_spectrum: 0.75931
title: 'Scrum | ITIL | Project Consulting'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a17'
    - '#fefefe'
    - '#7a6051'
    - '#a09baa'
    - '#972712'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
