name: 'lexiconic, inc.'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17963
title: Where does the title actually appear?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f40019'
    - '#0c0608'
    - '#fffffd'
    - '#b36d23'
    - '#dfa544'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
