name: lexiconic
favicon: null
layout_spectrum: 0.5871415254659951
typography_spectrum: 0.12238317262381315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010a0e'
    - '#f8f8f8'
    - '#385d4d'
    - '#cdc6c7'
    - '#ad784f'
  brandStrength: 0.5915853844489902
  lightness: 0.27970727370120585
  saturation: 0.038424830650910735
  rhythmicContrast: 0.8189691395964473
purpose: []
