name: 'lexiconic, inc.'
favicon: null
layout_spectrum: 0.67346
typography_spectrum: 0.83384
title: 'Scrum | ITIL | Project Consulting'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f6f9'
    - '#28411a'
    - '#de1b21'
    - '#d0c3bc'
    - '#af6f49'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
